/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Kanji
 */
public class UniversidadGrupo57 extends javax.swing.JFrame {

    /**
     * Creates new form UniversidadGrupo57
     */
    public UniversidadGrupo57() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbAlumno = new javax.swing.JMenu();
        miFormularioAlumno = new javax.swing.JMenuItem();
        mbMateria = new javax.swing.JMenu();
        miFormularioMateria = new javax.swing.JMenuItem();
        mbAdministracion = new javax.swing.JMenu();
        MiMenuInscripciones = new javax.swing.JMenuItem();
        miNotas = new javax.swing.JMenuItem();
        mbConsultas = new javax.swing.JMenu();
        miAlumnosPorMateria = new javax.swing.JMenuItem();
        mbSalir = new javax.swing.JMenu();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("File");
        jMenuBar3.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar3.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDEscritorioLayout = new javax.swing.GroupLayout(jDEscritorio);
        jDEscritorio.setLayout(jDEscritorioLayout);
        jDEscritorioLayout.setHorizontalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        jDEscritorioLayout.setVerticalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jDEscritorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDEscritorio)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jDEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mbAlumno.setText("Alumno");
        mbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbAlumnoActionPerformed(evt);
            }
        });

        miFormularioAlumno.setText("Formulario de Alumno");
        miFormularioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFormularioAlumnoActionPerformed(evt);
            }
        });
        mbAlumno.add(miFormularioAlumno);

        jMenuBar1.add(mbAlumno);

        mbMateria.setText("Materia");

        miFormularioMateria.setText("Formulario de Materia");
        miFormularioMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFormularioMateriaActionPerformed(evt);
            }
        });
        mbMateria.add(miFormularioMateria);

        jMenuBar1.add(mbMateria);

        mbAdministracion.setText("Administración");

        MiMenuInscripciones.setText("Manejo de Inscripciones");
        mbAdministracion.add(MiMenuInscripciones);

        miNotas.setText("Manipulación de notas");
        mbAdministracion.add(miNotas);

        jMenuBar1.add(mbAdministracion);

        mbConsultas.setText("Consultas");

        miAlumnosPorMateria.setText("Alumnos por Materia");
        mbConsultas.add(miAlumnosPorMateria);

        jMenuBar1.add(mbConsultas);

        mbSalir.setText("Salir");
        jMenuBar1.add(mbSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miFormularioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFormularioAlumnoActionPerformed
        // TODO add your handling code here:
         jDEscritorio.removeAll();
        jDEscritorio.repaint();
        GestionAlumnos gp= new GestionAlumnos();
        gp.setVisible(true);
        jDEscritorio.add(gp);
        jDEscritorio.moveToFront(gp);
       
    }//GEN-LAST:event_miFormularioAlumnoActionPerformed

    private void mbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbAlumnoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_mbAlumnoActionPerformed

    private void miFormularioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFormularioMateriaActionPerformed
       
         jDEscritorio.removeAll();
        jDEscritorio.repaint();
        GestionMaterias gp= new GestionMaterias();
        gp.setVisible(true);
        jDEscritorio.add(gp);
        jDEscritorio.moveToFront(gp);
        
    }//GEN-LAST:event_miFormularioMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniversidadGrupo57.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniversidadGrupo57.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniversidadGrupo57.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniversidadGrupo57.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UniversidadGrupo57().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MiMenuInscripciones;
    private javax.swing.JDesktopPane jDEscritorio;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu mbAdministracion;
    private javax.swing.JMenu mbAlumno;
    private javax.swing.JMenu mbConsultas;
    private javax.swing.JMenu mbMateria;
    private javax.swing.JMenu mbSalir;
    private javax.swing.JMenuItem miAlumnosPorMateria;
    private javax.swing.JMenuItem miFormularioAlumno;
    private javax.swing.JMenuItem miFormularioMateria;
    private javax.swing.JMenuItem miNotas;
    // End of variables declaration//GEN-END:variables
}
/*JDestokPane: escritorio
en el codigo
escritorio.removeAll(;
escritorio.repaint();
GestionAlumnos gp= new GestionAlumnos();
gp.setVisible(true);
escritorio.add(gp);
escritorio.moveToFront(gp)*/